# Your access token for character.AI
# See https://github.com/kramcat/CharacterAI for more information
# Requires a full reload of the bot for changes to take effect
token: "YOUR_TOKEN_HERE"

# The character's id to use if no other one is specified at chat creation
# You can leave it empty, in which case it will raise an error if no character is specified
# It's the value after the ?char= in the chat url
default_character_id: ""

# Who is allowed to use the bot?
# Leave empty to allow everyone
# List of mxids
allowed_users: []

# The string (case-insensitive) that a message must contain for the bot to reply.
# Leave empty to reply to every message
# Set to '{name}' to use the bot's mxid
trigger: "{name}"

# If true, the bot will strip the trigger from the message before sending it to the AI
# It will only strip it if it's at the very start of the message, so you can still use a bot's
# name in the middle of a sentence for example
strip_trigger_prefix: true

# If true, the bot will reply to messages that answer it
# even without the trigger matching
reply_is_trigger: true

# If true, the bot will always reply to messages in DMs
# even if the message didn't trigger it
always_reply_in_dm: true

# If true, the bot will use a reply to the triggering message
# otherwise, it just sends a message to the room without replying
reply_to_message: false

# If true, the bot will show the prompt used alongside the AI's reply
# If none, it will only show the prompt when in a group chat
# The prompt will be in a blockquote
show_prompt_in_reply: null

# If true, the bot will use the character.ai char's name as
# its display name ONLY for the current room.
# If false, it will use it's global display name.
use_char_name: true
# Same as above, but for the avatar.
# The avatar will be redownloaded and uploaded every time you
# start a new chat, so it can end up using some space.
use_char_avatar: false

# If true, the bot will prefix all messages with the name of the sender
# when communicating with the AI, useful for group chats.
# If false, it will never use the prefix.
# If null, it will automatically choose based on if a room is a group chat
group_mode: null

# The template to use for messages when group_mode is active
# {username} will be replaced with the username of the sender
# {text} will be replaced with the original message
# My suggestion is '{username}: {text}' or '*{username} says* {text}'
group_mode_template: "{username}: {text}"

# When a new chat is created, exports the previous chat's messages
# These options all have the same effect, but with different output format
# If multiple output formats are enabled, they will all be sent in one zip file
export_txt: false
