---
name: "Build plugin"

on: [push, workflow_dispatch]

jobs:
  build_plugin:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v4"
        with:
          lfs: true
          fetch-depth: 0

      - name: "Setup Python 3.10"
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: "Install Poetry"
        run: "pip3 install poetry"

      - name: "Install the project dependencies"
        run: "poetry install"

      - name: "Build plugin"
        run: "poetry run mbc build"

      - name: "Upload plugin"
        uses: actions/upload-artifact@v3
        with:
          name: "maubot-characterai"
          path: "*.mbp"
